services:
  - type: web
    name: taskhive
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: TaskHive
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://taskhive.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: taskhive-db
          property: connectionString
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: array
      - key: LOG_CHANNEL
        value: stderr

databases:
  - name: taskhive-db
    plan: free
    databaseName: taskhive
    user: taskhive
